### ISSUE TITLE
python3.x系だとドキュメント通りpipでインストールできない？

### ISSUE THREAD

**Issue by saxsir** [idcf/cloudstack-api#3]
http://docs.idcf.jp/cloud/introduction/#install

を見てインストールを試したが、以下のエラーでこけた。
`parsedatetime` のインストールでこけているのでそちらに書くべきかもしれないが、既知であればドキュメントにpythonのバージョンが明記されていると嬉しい。

```
$ python --version
Python 3.5.0

$ pip install git+https://github.com/idcf/cloudstack-api
Collecting git+https://github.com/idcf/cloudstack-api
  Cloning https://github.com/idcf/cloudstack-api to /var/folders/rk/wc59v43j6_922v54_kvk3_x80000gn/T/pip-n611etvb-build
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/var/pyenv/versions/venv3.5.0-smafle/lib/python3.5/site-packages (from cloudstack.compute==0.10.2)
Collecting httplib2 (from cloudstack.compute==0.10.2)
  Using cached httplib2-0.9.2.tar.gz
Collecting simplejson (from cloudstack.compute==0.10.2)
  Using cached simplejson-3.8.1.tar.gz
Collecting argparse (from cloudstack.compute==0.10.2)
  Using cached argparse-1.4.0-py2.py3-none-any.whl
Collecting prettytable==0.5 (from cloudstack.compute==0.10.2)
  Using cached prettytable-0.5.tar.gz
Collecting parsedatetime==0.8.7 (from cloudstack.compute==0.10.2)
  Using cached parsedatetime-0.8.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/rk/wc59v43j6_922v54_kvk3_x80000gn/T/pip-build-6rdmnj58/parsedatetime/setup.py", line 3, in <module>
        import ez_setup
      File "/private/var/folders/rk/wc59v43j6_922v54_kvk3_x80000gn/T/pip-build-6rdmnj58/parsedatetime/ez_setup.py", line 91
        except pkg_resources.VersionConflict, e:
                                            ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/rk/wc59v43j6_922v54_kvk3_x80000gn/T/pip-build-6rdmnj58/parsedatetime
```

**Comment by saxsir** [comment]
python2.7.10では正常にインストールできることを確認済み。

```
$ python --version
Python 2.7.10

$ pip install git+https://github.com/idcf/cloudstack-api
Collecting git+https://github.com/idcf/cloudstack-api
  Cloning https://github.com/idcf/cloudstack-api to /var/folders/rk/wc59v43j6_922v54_kvk3_x80000gn/T/pip-FHN6nQ-build
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/var/pyenv/versions/venv2.7.10-sandbox/lib/python2.7/site-packages (from cloudstack.compute==0.10.2)
Collecting httplib2 (from cloudstack.compute==0.10.2)
  Using cached httplib2-0.9.2.tar.gz
Collecting simplejson (from cloudstack.compute==0.10.2)
  Using cached simplejson-3.8.1.tar.gz
Collecting argparse (from cloudstack.compute==0.10.2)
  Using cached argparse-1.4.0-py2.py3-none-any.whl
Collecting prettytable==0.5 (from cloudstack.compute==0.10.2)
  Using cached prettytable-0.5.tar.gz
Collecting parsedatetime==0.8.7 (from cloudstack.compute==0.10.2)
  Using cached parsedatetime-0.8.7.tar.gz
Collecting lxml (from cloudstack.compute==0.10.2)
  Downloading lxml-3.4.4.tar.gz (3.5MB)
    100% |████████████████████████████████| 3.5MB 132kB/s
Building wheels for collected packages: httplib2, simplejson, prettytable, parsedatetime, lxml
  Running setup.py bdist_wheel for httplib2
  Stored in directory: /Users/saxsir/Library/Caches/pip/wheels/e1/a3/05/e66aad1380335ee0a823c8f1b9006efa577236a24b3cb1eade
  Running setup.py bdist_wheel for simplejson
  Stored in directory: /Users/saxsir/Library/Caches/pip/wheels/4e/25/10/2ff5f7347927f4816794414d599a5383c7f8dd9a9ff729af28
  Running setup.py bdist_wheel for prettytable
  Stored in directory: /Users/saxsir/Library/Caches/pip/wheels/a3/77/cb/7ea6f9a9099c10e825c05fc6c08e86713b8f5a002ba1aa35da
  Running setup.py bdist_wheel for parsedatetime
  Stored in directory: /Users/saxsir/Library/Caches/pip/wheels/f7/59/61/2e481135c99220d608506a1c996fb3685938f7e592aa762a9a
  Running setup.py bdist_wheel for lxml
  Stored in directory: /Users/saxsir/Library/Caches/pip/wheels/62/29/26/11383932dbed36e9fe68552fc755a96cfc6fa5833d948620da
Successfully built httplib2 simplejson prettytable parsedatetime lxml
Installing collected packages: httplib2, simplejson, argparse, prettytable, parsedatetime, lxml, cloudstack.compute
  Running setup.py install for cloudstack.compute
Successfully installed argparse-1.4.0 cloudstack.compute-0.10.2 httplib2-0.9.2 lxml-3.4.4 parsedatetime-0.8.7 prettytable-0.5 simplejson-3.8.1
```

**Comment by akito1986** [comment]
issue有難うございますmm

> parsedatetime のインストールでこけているのでそちらに書くべきかもしれないが、既知であればドキュメントにpythonのバージョンが明記されていると嬉しい。

こちら既知となり、今のところPython2.7+でないと動かないですね。。。ドキュメントに不備がありすいません。

取り急ぎ,Github上の[README.md](https://github.com/idcf/cloudstack-api)は修正しておきました。

- ドキュメントサイト(http://docs.idcf.jp/cloud/introduction/)
- setup.py

は修正次第このissueに記載させて頂きます。

**Comment by saxsir** [comment]
対応いただきありがとうございます！ > README
